#!/bin/bash
.venv/bin/python3 src/cvn/alexnet/classification/train.py \
  -dt "data/train" -dv "data/val" -nc 35 \
  --img-channels 3 --img-size 224 \
  -n 200 -b 8 -lr 1e-4 -gas 384 \
  --checkpoint-dir "checkpoints" -r "checkpoints/checkpoint.pth" \
  --model-file "saved_model" --freeze-feature-layers
