#!/bin/bash
python src/cvn/alexnet/classification/train.py \
  -dt "data/train" -dv "data/val" -nc 35 \
  --img-channels 3 --img-size 224 \
  -n 100 -b 8 -lr 0.001 -gas 384 \
  --checkpoint-dir "checkpoints" -r "checkpoints/checkpoint.pth"
  # --model-file "saved_model"

